<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
date_default_timezone_set("Europe/Moscow");
setlocale(LC_ALL, 'ru_RU');
session_start();
$config = require __DIR__.'/config.php';
require_once 'function.php';
require_once 'vendor/autoload.php';
require_once __DIR__.'/functions/view.php';
require_once __DIR__.'/functions/db/db.php';
require_once __DIR__.'/functions/db/search.php';
require_once __DIR__.'/functions/db/categories.php';
require_once __DIR__.'/functions/db/lot.php';
require_once __DIR__.'/functions/db/lotdetail.php';
require_once __DIR__.'/functions/db/login.php';
require_once __DIR__.'/functions/db/my_bets.php';
require_once __DIR__.'/functions/db/registration.php';
require_once __DIR__.'/functions/validators/lot.php';
require_once __DIR__.'/functions/validators/bet.php';
require_once __DIR__.'/functions/form/lot.php';
require_once __DIR__.'/functions/validators/validate_registration_form.php';
require_once __DIR__.'/functions/validators/validate_login_form.php';
$connection = db_connect($config['db']);
